export const data = [
  // GREETINGS
  {
    id: "greeting1",
    wolof: "Nuyu naala",
    english: "Hello / Greetings",
    category: "greetings & farwells",
  },
  {
    id: "greeting2",
    wolof: "Asalaa maalekum",
    english: "Peace be upon you",
    category: "greetings & farwells",
  },
  {
    id: "greeting2",
    wolof: "{In response to above} Maalekum salaam",
    english: "Peace be upon you",
    category: "greetings & farwells",
  },
  {
    id: "greeting3",
    wolof: "Nanga def?",
    english: "How are you?",
    category: "greetings & farwells",
  },
  {
    id: "greeting",
    wolof: "Naka moo",
    english: "What's up?",
    category: "greetings & farwells"
  },
  {
    id: "greeting3",
    wolof: "Maangi fii, jarajëf / Jámm rekk",
    english: "Fine, thanks / Peace only",
    category: "greetings & farwells",
  },
  {
    id: "greeting4",
    wolof: "Naka waa kër gi?",
    english: "How is the family?",
    category: "greetings & farwells",
  },
  {
    id: "greeting5",
    wolof: "Ñungi fi",
    english: "They are fine",
    category: "greetings & farwells",
  },
  {
    id: "greeting6",
    wolof: "Naka suba si?",
    english: "How is the morning?",
    category: "greetings & farwells",
  },
  {
    id: "greeting6",
    wolof: "Guddig jàmm",
    english: "Good evening",
    category: "greetings & farwells",
  },
  {
    id: "greeting7",
    wolof: "Ñu fanaan ci jàmm ",
    english: "Good night",
    category: "greetings & farwells",
  },
  {
    id: "greeting7",
    wolof: "Ba beneen yóon",
    english: "Goodbye / See you next time",
    category: "greetings & farwells",
  },
  // INTRODUCTIONS
  {
    id: "intro1",
    wolof: "Noo tuddu?",
    english: "What's your name?",
    category: "introductions",
  },
  {
    id: "intro2",
    wolof: "Amy laa tuddu, yow nag?",
    english: "My name is Amy, what's yours?",
    category: "introductions",
  },
  {
    id: "intro2",
    wolof: "Noo sant? / Nanga sant? / Naka nga sant?",
    english: "What is your last name?",
    category: "introductions",
  },
  {
    id: "intro2",
    wolof: "Lopez laa sant",
    english: "My last name is Lopez",
    category: "introductions",
  },
  {
    id: "intro4",
    wolof: "Ñaata at nga am?",
    english: "How old are you?",
    category: "introductions",
  },
  {
    id: "intro5",
    wolof: "Fanweer at laa am",
    english: "I'm 30",
    category: "introductions",
  },
  {
    id: "intro6",
    wolof: "Fo jòge?",
    english: "Where do you come from?",
    category: "introductions",
  },
  {
    id: "intro7",
    wolof: "United States laa dëkk",
    english: "I'm from the United States",
    category: "introductions",
  },
  {
    id: "intro7",
    wolof: "Foo dëkk",
    english: "Where do you live?",
    category: "introductions",
  },
  {
    id: "intro7",
    wolof: "London laa dëkk",
    english: "I live in London",
    category: "introductions",
  },
  // ESSENTIAL WORDS
  {
    id: "essentialword1",
    wolof: "Waaw",
    english: "Yes",
    category: "essential words",
  },
  {
    id: "essentialword2",
    wolof: "Déet/Déedéet",
    english: "No",
    category: "essential words",
  },
  {
    id: "essentialword3",
    wolof: "Waaw-kay ",
    english: "OK",
    category: "essential words",
  },
  {
    id: "essentialword4",
    wolof: "Baal ma",
    english: "Sorry / Excuse me",
    category: "essential words",
  },
  {
    id: "essentialword5",
    wolof: "Léegi",
    english: "Soon",
    category: "essential words",
  },
  {
    id: "essentialword6",
    wolof: "Dara",
    english: "Nothing",
    category: "essential words",
  },
  {
    id: "essentialword7",
    wolof: "Xaaral",
    english: "Wait",
    category: "essential words",
  },
  // BASIC PHRASES
  {
    id: "basicphrase1",
    wolof: "Nga baalma ",
    english: "Excuse me",
    category: "basic phrases",
  },
  {
    id: "basicphrase2",
    wolof: "Jërëjëf",
    english: "Thank you",
    category: "basic phrases",
  },
  {
    id: "basicphrase3",
    wolof: "Ñoo ko bokk",
    english: "You're welcome",
    category: "basic phrases",
  },
  {
    id: "basicphrase4",
    wolof: "Baax na, jërëjëf",
    english: "No thanks",
    category: "basic phrases",
  },
  {
    id: "basicphrase5",
    wolof: "Xamuma ",
    english: "I don't know",
    category: "basic phrases",
  },
  {
    id: "basicphrase6",
    wolof: "Ayca ñu dem",
    english: "Let's go",
    category: "basic phrases",
  },
  {
    id: "basicphrase7",
    wolof: "Duma tux",
    english: "I don't smoke",
    category: "basic phrases",
  },
  // BASIC QUESTIONS
  {
    id: "basicquestion1",
    wolof: "Kan?",
    english: "Who?",
    category: "basic questions",
  },
  {
    id: "basicquestion2",
    wolof: "Lan?",
    english: "What?",
    category: "basic questions",
  },
  {
    id: "basicquestion3",
    wolof: "Kañ?",
    english: "When?",
    category: "basic questions",
  },
  {
    id: "basicquestion4",
    wolof: "Fan?",
    english: "Where?",
    category: "basic questions",
  },
  {
    id: "basicquestion5",
    wolof: "Lu tax?",
    english: "Why?",
    category: "basic questions",
  },
  {
    id: "basicquestion5",
    wolof: "Naka",
    english: "How?",
    category: "basic questions",
  },
  {
    id: "basicquestion5",
    wolof: "Ñaata",
    english: "How many?",
    category: "basic questions",
  },
  {
    id: "basicquestion4",
    wolof: "Ndax?",
    english: "Is it that?",
    category: "basic questions",
  },
  {
    id: "basicquestion4",
    wolof: "Ban?",
    english: "Which?",
    category: "basic questions",
  },
  {
    id: "basicquestion6",
    wolof: "Ban waxtu moo jot?",
    english: "What time is it?",
    category: "basic questions",
  },
  // COMPREHENSION
  {
    id: "comprehension4",
    wolof: "Dégguma Wolof bu baax",
    english: "I don't speak much Wolof",
    category: "comprehension",
  },
  {
    id: "comprehension4",
    wolof: "Maangiy jang Wolof ndank-ndank",
    english: "I'm learning Wolof small-small",
    category: "comprehension",
  },
  {
    id: "comprehension1",
    wolof: "Xawma li nga bëgg wax",
    english: "I don't understand",
    category: "comprehension",
  },
  {
    id: "comprehension2",
    wolof: "Baamtuwaat ko, nga baalma?",
    english: "Can you repeat that please?",
    category: "comprehension",
  },
  {
    id: "comprehension3",
    wolof: "Waxal ndank",
    english: "Please speak more slowly",
    category: "comprehension",
  },
  {
    id: "comprehension5",
    wolof: "Mahn deggouma Farnes",
    english: "I don't speak French",
    category: "comprehension",
  },
  // SHOPPING
  {
    id: "shopping1",
    wolof: "Bii ñaata lay jar?",
    english: "How much does this cost?",
    category: "shopping",
  },
  {
    id: "shopping2",
    wolof: "Bii laa bëgg jënd",
    english: "I'd like to buy this",
    category: "shopping",
  },
  {
    id: "shopping3",
    wolof: "Ubbi",
    english: "Open",
    category: "shopping",
  },
  {
    id: "shopping4",
    wolof: "Tëjna",
    english: "Closed",
    category: "shopping",
  },
  // FOOD/DRINK
  {
    id: "food2",
    wolof: "Loo bëgg naan",
    english: "What would you like to drink?",
    category: "food/drink",
  },
  {
    id: "food3",
    wolof: "Loo bëgg lekk?",
    english: "What would you like to eat?",
    category: "food/drink",
  },
  {
    id: "food4",
    wolof: "Looñuy digël?",
    english: "What do you recommend?",
    category: "food/drink",
  },
  {
    id: "food5",
    wolof: "Lii lan la?",
    english: "What is this?",
    category: "food/drink",
  },
  {
    id: "food6",
    wolof: "Bumu sàf kaani lool, nga baalma",
    english: "Not too spicy, please",
    category: "food/drink",
  },
  {
    id: "food7",
    wolof: "Suurnaa!",
    english: "I'm full!",
    category: "food/drink",
  },
  {
    id: "food8",
    wolof: "Ndox",
    english: "Water",
    category: "food/drink",
  },
  {
    id: "food9",
    wolof: "Galaas",
    english: "Ice",
    category: "food/drink",
  },
  {
    id: "food10",
    wolof: "Meew",
    english: "Milk",
    category: "food/drink",
  },
  // TRAVEL
  {
    id: "travel1",
    wolof: "Fan la mënee am ab taksi?",
    english: "Where can I get a taxi?",
    category: "travel",
  },
  {
    id: "travel2",
    wolof: "Taksi",
    english: "Taxi",
    category: "travel",
  },
  {
    id: "travel3",
    wolof: "Saxaar",
    english: "Train",
    category: "travel",
  },
  {
    id: "travel4",
    wolof: "Gaaru saxaar",
    english: "Train station",
    category: "travel",
  },
  {
    id: "travel5",
    wolof: "Biis",
    english: "Bus",
    category: "travel",
  },
  {
    id: "travel6",
    wolof: "Paasapór",
    english: "Passport",
    category: "travel",
  },
  {
    id: "travel7",
    wolof: "Ayrapoor",
    english: "Airport",
    category: "travel",
  },
  {
    id: "travel8",
    wolof: "Rapalaan",
    english: "Plane",
    category: "travel",
  },
  {
    id: "travel9",
    wolof: "Otel",
    english: "Hotel",
    category: "travel",
  },
  // DIRECTIONS
  {
    id: "directions1",
    wolof: "Càmmoñ",
    english: "Left",
    category: "directions",
  },
  {
    id: "directions2",
    wolof: "Ndeyjóor",
    english: "Right",
    category: "directions",
  },
  {
    id: "directions2",
    wolof: "Ani wanag yi?",
    english: "Where are the toilets?",
    category: "directions",
  },
  {
    id: "directions3",
    wolof: "Ani tefes gi?",
    english: "Where is the beach?",
    category: "directions",
  },
  {
    id: "directions4",
    wolof: "Ani bank bi?",
    english: "Where is the bank?",
    category: "directions",
  },
  {
    id: "directions5",
    wolof: "Ani polis bi?",
    english: "Where is the police station?",
    category: "directions",
  },
  {
    id: "directions6",
    wolof: "Nan laay def ba egg fofu?",
    english: "How do I get there?",
    category: "directions",
  },
  {
    id: "directions7",
    wolof: "Damaa reer",
    english: "I'm lost",
    category: "directions",
  },
  // NUMBERS
  {
    id: "numbers1",
    wolof: "Benn",
    english: "One",
    category: "numbers",
  },
  {
    id: "numbers2",
    wolof: "Ñaar",
    english: "Two",
    category: "numbers",
  },
  {
    id: "numbers3",
    wolof: "Ñett",
    english: "Three",
    category: "numbers",
  },
  // FEELINGS
  {
    id: "feelings1",
    wolof: "Dama màr",
    english: "I'm thirsty",
    category: "feelings",
  },
  {
    id: "feelings2",
    wolof: "Dama xiif",
    english: "I'm hungry",
    category: "feelings",
  },
  {
    id: "feelings3",
    wolof: "Dama sonn",
    english: "I'm tired",
    category: "feelings",
  },
  {
    id: "feelings4",
    wolof: "Dama liw ",
    english: "I'm cold",
    category: "feelings",
  },
  {
    id: "feelings5",
    wolof: "Dama tàng",
    english: "I'm hot",
    category: "feelings",
  },
  {
    id: "feelings6",
    wolof: "Dama mér",
    english: "I'm angry",
    category: "feelings",
  },
  {
    id: "feelings7",
    wolof: "Dama mer ba futtu",
    english: "I'm frustrated",
    category: "feelings",
  },
  // ADJECTIVES
  {
    id: "adjective1",
    wolof: "Rafet",
    english: "Beautiful",
    category: "adjectives",
  },
  {
    id: "adjective2",
    wolof: "Amul Dara",
    english: "Empty",
    category: "adjectives",
  },
];
